version: '3'

services:
  gestion-rh-app:
    image: belhassen12/backrh-1.0.0:1.0
    container_name: gestion-rh-app
    ports:
      - "8090:8090"
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/GRH
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:mysql://gestion-rh-db:3306/GESTION-RH?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=rhuser
      - SPRING_DATASOURCE_PASSWORD=rhpass
    depends_on:
      - gestion-rh-db
      - logstash  # Assurez-vous que l'application dépend de Logstash pour les logs

  gestion-rh-db:
    image: mysql:latest
    container_name: gestion-rh-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: GESTION-RH
      MYSQL_USER: rhuser
      MYSQL_PASSWORD: rhpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    ports:
      - "5000:5000"
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  mysql_data:
  esdata1:
    driver: local
